### ISSUE TITLE
OFS Extension MTFG Starts with default settings.  Changed settings do not persist.

### ISSUE THREAD

**Issue by OverKillEngine** [michael-mueller-git/Python-Funscript-Editor#12]
OFS Extension MTFG Starts with default settings.  Changed settings do not persist. 
![image](https://user-images.githubusercontent.com/13063265/142428463-510eca05-5ddc-450f-949d-3ce1293ca3ee.png)

OFS Windows Version: 1.4.2@8fabb92
MTFG Windows Version: 0.1.6

**Comment by michael-mueller-git** [comment]
With Version v0.1.7 the settings dialog should be persistent. If something does not work or is unclear simply open the issue again.
