### ISSUE TITLE
Name: HEUR:Trojan-Downloader.Win32.Pyfatget.gen

### ISSUE THREAD

**Issue by puste1** [michael-mueller-git/Python-Funscript-Editor#14]
This comes up in the exe file when try to download. mtfg-ofs-extension-installer-v0.0.3.exe

**Comment by michael-mueller-git** [comment]
This should be a false positive message from your antivirus software. It could of course be possible that e.g. one of the dependencies is provided with malicious code. But that is very very unlikely.! If you don't trust the released `exe` files you can download the source code and check them for malicious code. Then you can[ build the application locally](https://github.com/michael-mueller-git/Python-Funscript-Editor/blob/main/docs/app/docs/user-guide/build.md) on your computer. You can also build the Installer with [this instruction](https://github.com/michael-mueller-git/Python-Funscript-Editor/tree/main/contrib/Installer).

**Comment by duck313** [comment]
Il giorno mar 4 gen 2022 alle ore 21:10 michael-mueller-git <
***@***.***> ha scritto:

**Comment by michael-mueller-git** [comment]
See also:
- https://github.com/pyinstaller/pyinstaller/issues/4633
- https://github.com/pyinstaller/pyinstaller/issues/5854
- https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg
- https://www.reddit.com/r/learnpython/comments/itlai0/pyinstaller_issues_exe_identified_as_trojan/
- ...
