### ISSUE TITLE
Distance inverted returns same result as Distance

### ISSUE THREAD

**Issue by trassshhub** [michael-mueller-git/Python-Funscript-Editor#21]
**Describe the bug**
distance inverted (p2-p1) returns same result as distance (p1-p2).

**To Reproduce**
Do two trackings with same targets and parameters, except one with "distance inverted" and one with "distance" as tracking metric.
Results are the same.

**Expected behavior**
Expecting "distance" to return result with higher values when 2 targets are further apart and smaller values when targets are closer, while "distance inverted" should return smaller values when targets are further apart and higher values targets are closer,

**Runtime:**
- OS: Windows 10
- Version: 0.5.0

**Additional context**
Can I have a further explanation on the need of selecting center line after distance-based tracking? Is it for projection? Is it possible to return the raw distance between the two points?

**Comment by michael-mueller-git** [comment]
Thanks for reporting. Bug also apply to y and x. Fixed with 6d11368. Invert functions will be functional again in the next release version.

**Comment by michael-mueller-git** [comment]
> Can I have a further explanation on the need of selecting center line after distance-based tracking?

Is mainly relevant for roll prediction to determine the actual turning point. The program calculate the offset values for tracked feature and the selected start and endpoint of the center line. (We could theoretically remove this for  distance prediction. But for simpler program structure i include the menu for all options).

> Is it possible to return the raw distance between the two points?

Only the normalized raw distance: Enable the [raw_output](https://github.com/michael-mueller-git/Python-Funscript-Editor/blob/v0.5.0/funscript_editor/config/settings.yaml#L30) in the config file and select option `distance (p1-p2)` or the inverted equivalent.

**Comment by michael-mueller-git** [comment]
fixed in [v0.5.1](https://github.com/michael-mueller-git/Python-Funscript-Editor/releases/tag/v0.5.1)
